codecloud_shopify_auth:
    path: /shopify/auth
    controller: CodeCloud\Bundle\ShopifyBundle\Controller\OAuthController::auth

codecloud_shopify_verify:
    path: /shopify/verify
    controller: CodeCloud\Bundle\ShopifyBundle\Controller\OAuthController::verify

codecloud_shopify_webhooks:
    path: /shopify/webhooks
    controller: CodeCloud\Bundle\ShopifyBundle\Controller\WebhookController::handleWebhook
