services:
  codecloud_shopify.store_manager:
    synthetic: true
    alias: ~ # this is configured via bundle extension

  CodeCloud\Bundle\ShopifyBundle\Controller\OAuthController:
    public: true
    arguments:
      $router: "@router"
      $config: "%codecloud_shopify.oauth%"
      $client: '@GuzzleHttp\Client'
      $stores: "@codecloud_shopify.store_manager"
      $dispatcher: "@event_dispatcher"
      $hmacSignature: '@CodeCloud\Bundle\ShopifyBundle\Security\HmacSignature'

  CodeCloud\Bundle\ShopifyBundle\Controller\WebhookController:
    public: true
    arguments:
      $storeManager: "@codecloud_shopify.store_manager"
      $eventDispatcher: "@event_dispatcher"

  CodeCloud\Bundle\ShopifyBundle\Command\WebhooksCommand:
    arguments:
      $webhookCreator: '@CodeCloud\Bundle\ShopifyBundle\Service\WebhookCreator'
      $storeManager: "@codecloud_shopify.store_manager"
      $topics: "%codecloud_shopify.webhooks%"
    tags:
      - { name: console.command }

  CodeCloud\Bundle\ShopifyBundle\EventListener\WebhookLoggerListener:
    arguments:
      $logger: "@logger"
    tags:
      - { name: kernel.event_subscriber }

  GuzzleHttp\Client: ~

  CodeCloud\Bundle\ShopifyBundle\Api\HttpClientFactory:
    public: false

  CodeCloud\Bundle\ShopifyBundle\Api\ShopifyApiFactory:
    arguments:
      $storeManager: "@codecloud_shopify.store_manager"
      $httpClientFactory: '@CodeCloud\Bundle\ShopifyBundle\Api\HttpClientFactory'

  CodeCloud\Bundle\ShopifyBundle\Security\HmacSignature:
    public: false
    arguments:
      $sharedSecret: "%codecloud_shopify.oauth.shared_secret%"

  CodeCloud\Bundle\ShopifyBundle\Security\SessionAuthenticator:
    public: false
    arguments:
      $urlGenerator: "@router"

  CodeCloud\Bundle\ShopifyBundle\Security\ShopifyAdminUserProvider:
    public: false
    arguments:
      $storeManager: "@codecloud_shopify.store_manager"

  CodeCloud\Bundle\ShopifyBundle\Twig\Extension\ShopifyStore:
    arguments:
      $hmac: '@CodeCloud\Bundle\ShopifyBundle\Security\HmacSignature'
    tags:
      - { name: twig.extension }

  CodeCloud\Bundle\ShopifyBundle\Service\WebhookCreator:
    arguments:
      $apis: '@CodeCloud\Bundle\ShopifyBundle\Api\ShopifyApiFactory'
      $router: "@router"

  CodeCloud\Bundle\ShopifyBundle\EventListener\SessionAuthenticationListener:
    class:
    arguments:
      $requestStack: "@request_stack"
    tags:
      - { name: kernel.event_subscriber }
